sonata_block:
    default_contexts: [symfony_web_app]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.rss: ~
        sonata.admin.block.search_result:
            contexts:   [admin]
        sonata.user.block.menu: ~


sonata_admin:
    title: %project_name%
    title_logo: /bundles/appbackend/images/logo.png
    templates:
        # default global templates
        layout:    ::standard_layout.html.twig
        ajax:      SonataAdminBundle::ajax_layout.html.twig
        
        # default values of actions templates, they should extend global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        # default values of helper templates
        short_object_description: SonataAdminBundle:Helper:short-object-description.html
    
    dashboard:
        blocks:
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [User] } }
            - { position: right,  type: sonata.admin.block.admin_list, settings: { groups: [admin] } }
        
        groups:
            User:
                roles: [ ROLE_SUPER_ADMIN ]
                label: 'Usuarios'
            admin: 
                roles: [ ROLE_SUPER_ADMIN ]
                label: 'Administrador'